version: '3'

services:

  db:
    container_name: db
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - psql-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"

  db-test:
    container_name: db-test
    image: postgres:14
    restart: always
    ports:
      - 5433:5432
    volumes:
      - psql-store-test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  psql-store:
    driver: local
  psql-store-test:
    driver: local
